import type { Metadata } from "next";
import "./globals.css";
import { MSWProvider } from "@/app/_component/MSWComponent";
import AuthSession from "@/app/_component/AuthSession";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production"
  // && process.env.NEXT_PUBLIC_MSW_ENABLED !== "false"
) {
  // eslint-disable-next-line
  const { server } = require("@/mocks/http");
  server.listen();
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MSWProvider>
          <AuthSession>{children}</AuthSession>
        </MSWProvider>
      </body>
    </html>
  );
}
